### ISSUE TITLE
Restore connection when logstash is restarted

### ISSUE THREAD

**Issue by inteloid** [jaakkos/winston-logstash#33]
subject says it all, is there a feature like that? or any plans to implement?

**Comment by bushev** [comment]
+1

**Comment by mitchjmiller** [comment]
In the options object passed to winston-logstash you can define max_connect_retries. This defaults to four with a 100ms interval judging by the code before giving up and going silent.
I ran into this issue myself when restarting logstash as winston-logstash would give up on the connection before the server had time to start up again.

Setting max_connect_retries to -1 (infinite) worked for me.
