### ISSUE TITLE
Improvement: force close method

### ISSUE THREAD

**Issue by RNiveau** [jaakkos/winston-logstash#34]
Hi guys,

I had a problem with my application and winston-logstash.

To avoid disconnection problem, I fixed the max_connect_retries to -1 (I did this because every two minutes without data, the connection was closed by remote host).
But, when my application close properly, I need to close the logger. With the -1 set, the logger was never closed because it attempted reconnection infinitely.

So to fixe my problem, I did this:

```
  logger.transports.logstash.max_connect_retries = 0;
  logger.close();
``` 

It works fine but it's not very nice.

Can you add a method to force close which doesn't try to reconnect ?

**Comment by djMax** [comment]
+1 - it also makes unit/integration tests not close properly because it immediately calls setTimeout after an explicit close.

**Comment by djMax** [comment]
Also there should probably be an event thrown when a flush completes, else you can't drain the log messages.

**Comment by djMax** [comment]
This should be fixed now as it will not reconnect after close is called.

**Comment by diwakar-s-maurya** [comment]
I am using winston@2.4.4 and able to replicate this problem.

Code to replicate it:
```javascript
const winston = require('winston')
require('winston-logstash')

const logger = new winston.Logger()

logger.add(winston.transports.Logstash, {
    host: 'localhost',
    max_connect_retries: -1, // -1 means retry forever.
    node_name: 'my node name',
    port: 28777
})

setTimeout(() => {
    logger.close()
}, 1000);
```

With max_connect_retries: -1, it never exits but with 0 it exits as expected after 1 second.
