### ISSUE TITLE
winston-logstash and npm v3.3.5 result in 'Unmet Peer Dependency'

### ISSUE THREAD

**Issue by gloddy** [jaakkos/winston-logstash#36]
After updating to npm v3.3.5, I get the following when trying to ```npm install``` a package.json that includes ```"winston-logstash": "^0.2.11"```

```
└── UNMET PEER DEPENDENCY winston@>=0.7.3
npm ERR! peer dep missing: winston@>=0.7.3, required by winston-logstash@0.2.11
```

**Comment by cjsaylor** [comment]
@gloddy npm changed how the peer dependencies work. They are no longer installed when declared and are up to the end user to include them in the dependencies list.

To resolve, you'll need to include `winston` in your `package.json`. See the `peerDependencies` section in the documentation: https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by gloddy** [comment]
Much thanks. Catching up on the npm v3 stuff.

**Comment by cjsaylor** [comment]
@gloddy No problem. In fairness, the readme should probably be updated with instructions to do this.
