### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by jaakkos** [jaakkos/winston-logstash#37]
Hi Everybody!

First of all I want to thank all the contributors and users! :)

I have not been able to keep up with open issues, changes to Winston and I am not using it my self in production any more. So I feel that I not right guy to steer this project. I am looking right people to take over :) 

If you are interested you can reply here or drop me email to jaakko@suutarla.com

thanks 
Jaakko

**Comment by strarsis** [comment]
What are you using in production now instead of winston/winston-logstash?

Thank you and
with best regards

**Comment by behrangsa** [comment]
@jaakkos,

I will be happy to take over its maintenance. We are heavily using it at SEEK at the moment.

Cheers,
Behrang

**Comment by d4goxn** [comment]
So, does this currently have a maintainer? The "looking for maintainers" message is still on the readme, along with a todo: rewrite. This does not inspire confidence ;p 17K downloads on npmjs does, though. I guess I'll just try this out and see how it goes.

@jaakkos I second @strarsis question: what did you move on to? Did you find a better way to send logs to logstash, or are you no longer using logstash at all?

**Comment by djMax** [comment]
I've become a maintainer here now, so closing this until I rage quit node.js sometime in the future.
