### ISSUE TITLE
winston.add() doesn't work?

### ISSUE THREAD

**Issue by AlvMF1** [jaakkos/winston-logstash#51]
If I add logstash transport in the constructor, I get the expected behavior (in this case, max retries reached error).
If using `winston.add()`, the transport fails silently...

Investigating, the differences I found were `_events` and `_eventsCount`:

```js
// node@8.10.0
// winston@2.4.1
// winston-logstash@0.4.0

'use strict'

const winston = require('winston')
require('winston-logstash')

const logger1 = new winston.Logger({
  transports: [
    new winston.transports.Logstash({
      host: '127.0.0.1',
      port: '8200',
      node_name: 'node_logger',
    }),
  ],
})

const logger2 = new winston.Logger()
logger2.add(winston.transports.Logstash, {
  host: '127.0.0.1',
  port: '8200',
  node_name: 'node_logger',
})

console.log(logger1.transports.logstash._events) // logs {}
console.log(logger2.transports.logstash._events) // logs { error: [Function: bound ] }
```

Am I doing something wrong? It'd be nice to use `.add()` in my case...

Thanks!

**Comment by dearsaturn** [comment]
@AlvMF1 were you able to get it working with `add`?

**Comment by AlvMF1** [comment]
Nope. I gave up...
I still need to do it, but it will be a raw TCP message to the Logstash server.

**Comment by dearsaturn** [comment]
Ok, we're (social native, where I work) going to make an alternative to this since we also really need it. Will more than likely open source it, and I will post here about it. If we don't end up wanting to open source it, I'll just gist you what the code looks like.
