### ISSUE TITLE
Winston didn't sent log to Logstash

### ISSUE THREAD

**Issue by alifsn** [jaakkos/winston-logstash#70]
Winston didn't sent log to Logstash, using winston version 3.8.2 and winston-logstash version 1.1.0, my node apps doesn't send any thing

**Comment by jaakkos** [comment]
Did you check the [test-bench](https://github.com/jaakkos/winston-logstash#run-integration-tests-with-logstash) code, which can be found in this repository? There is [minimal setup](https://github.com/jaakkos/winston-logstash/blob/main/test-bench/winston-3x/test/smoke_test.js) to ensure that everything is working. Could you point that to your local Logstash instance and ensure it's configured correctly?

**Comment by jaakkos** [comment]
I haven't heard anything back from the suggested debugging, and I'll close the issue for now.
