### ISSUE TITLE
How can i add application_name to the payload ? 

### ISSUE THREAD

**Issue by remihamy** [jaakkos/winston-logstash#79]
All is in the title :)

**Comment by jaakkos** [comment]
To add the application_name to the payload, you can simply include it as a key-value pair in the logger.info() function call, like this: `logger.info('Hello, logstash!', { application_name: 'My App' })`. This will ensure that the application name is included in the payload sent to Logstash.

Something like this should work:
```
const winston = require('winston');
require('winston-logstash');

const logger = winston.createLogger({
  transports: [
    new winston.transports.Logstash({
      port: 28777,
      node_name: 'my node name',
      host: '127.0.0.1'
    })
  ]
});

logger.info('Hello, logstash!', { application_name: 'My App' });

```
